#!/usr/bin/env bash
# env_probe.sh — per-host environment capability probe + registry writer.
#
# Workspace-level tool (IVG-TOOLENV-REGISTRY, hoisted 2026-07-11): one probe,
# shared by every project on this machine under ~/workspace. Writes a local
# per-host registry so agents and operators probe, don't recall. Behavior rule:
# .agents/rules/environment-truth.md.
# This script owns the execution knowledge; it emits GENERIC host capability facts
# only — per-project task->command mapping stays in each project's own governance.
#
# Usage:
#   scripts/env_probe.sh           probe everything, write .agents/env/<host>.yml
#   scripts/env_probe.sh --check   exit 0 if registry for this host exists and is
#                                  fresh (< TTL days); exit 1 with a hint otherwise
#
# TTL override: ENV_PROBE_TTL_DAYS=N (default 7)

set -euo pipefail

# Registry always lives at the workspace root (this script's parent-of-parent),
# regardless of which project's CWD invoked it — one shared registry per host.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOST_MARKER="$(hostname -s)"
REGISTRY_DIR="${REPO_ROOT}/.agents/env"
REGISTRY_FILE="${REGISTRY_DIR}/${HOST_MARKER}.yml"
TTL_DAYS="${ENV_PROBE_TTL_DAYS:-7}"

# Parse the ISO-8601 stamp this script writes, on either userland: GNU date
# takes -d, BSD date (macOS) needs an explicit -j -f parse, and Homebrew
# coreutils' gdate accepts the GNU form. Prints 0 when nothing can parse it, so
# an unreadable stamp still reads as stale rather than aborting the check.
iso_to_epoch() {
  local iso="$1" s
  s="$(date -d "$iso" +%s 2>/dev/null || true)"
  if [[ -z "$s" ]] && command -v gdate >/dev/null 2>&1; then
    s="$(gdate -d "$iso" +%s 2>/dev/null || true)"
  fi
  if [[ -z "$s" ]]; then
    s="$(date -u -j -f '%Y-%m-%dT%H:%M:%SZ' "$iso" +%s 2>/dev/null || true)"
  fi
  printf '%s' "${s:-0}"
}

# ── --check mode ────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--check" ]]; then
  if [[ ! -f "$REGISTRY_FILE" ]]; then
    echo "env-probe: no registry for host '${HOST_MARKER}' — run scripts/env_probe.sh first" >&2
    exit 1
  fi
  probed_at="$(grep -E '^probed_at:' "$REGISTRY_FILE" | head -1 | awk '{print $2}')"
  if [[ -z "$probed_at" ]]; then
    echo "env-probe: registry ${REGISTRY_FILE} has no probed_at — re-run scripts/env_probe.sh" >&2
    exit 1
  fi
  now_s="$(date +%s)"
  probed_s="$(iso_to_epoch "$probed_at")"
  age_days=$(( (now_s - probed_s) / 86400 ))
  if (( age_days >= TTL_DAYS )); then
    echo "env-probe: registry for '${HOST_MARKER}' is ${age_days}d old (TTL ${TTL_DAYS}d) — re-run scripts/env_probe.sh" >&2
    exit 1
  fi
  echo "env-probe: registry for '${HOST_MARKER}' is fresh (${age_days}d old, TTL ${TTL_DAYS}d)"
  exit 0
fi

# ── probe helpers ───────────────────────────────────────────────────────────
have() { command -v "$1" >/dev/null 2>&1; }

ver_or_absent() {
  # $1 = command, $2 = version args
  if have "$1"; then
    local v
    v="$($1 ${2:-"--version"} 2>/dev/null | head -1 | tr -d '"' || true)"
    echo "{available: true, version: \"${v}\"}"
  else
    echo "{available: false}"
  fi
}

# docker: distinguish CLI-present from daemon-reachable. Emit a COUNT of running
# containers, not their names — even local runtime evidence should avoid recording
# unrelated host infrastructure details.
probe_docker() {
  if ! have docker; then echo "{available: false, note: \"CLI not installed\"}"; return; fi
  local server
  if server="$(docker version --format '{{.Server.Version}}' 2>/dev/null)" && [[ -n "$server" ]]; then
    local running_count
    running_count="$(docker ps -q 2>/dev/null | wc -l | tr -d ' ')"
    echo "{available: true, daemon: true, server: \"${server}\", running_count: ${running_count}}"
  else
    echo "{available: true, daemon: false, note: \"CLI present, daemon unreachable\"}"
  fi
}

probe_gh() {
  if ! have gh; then echo "{available: false}"; return; fi
  if gh auth status >/dev/null 2>&1; then
    echo "{available: true, authenticated: true}"
  else
    echo "{available: true, authenticated: false}"
  fi
}

# Host-level git reachability proxy: probes REPO_ROOT's (= workspace-meta's)
# origin. Signals "this host has working git + network + auth to its git host",
# NOT that any given project's own remote is reachable.
probe_git_push() {
  if git -C "$REPO_ROOT" ls-remote origin HEAD >/dev/null 2>&1; then
    echo "{remote_reachable: true}"
  else
    echo "{remote_reachable: false}"
  fi
}

# ── write registry ──────────────────────────────────────────────────────────
# Write to a same-dir temp then atomically rename, so an interrupted probe never
# leaves a half-written (and then falsely "fresh") registry file.
mkdir -p "$REGISTRY_DIR"
REGISTRY_TMP="${REGISTRY_FILE}.tmp.$$"
trap 'rm -f "$REGISTRY_TMP"' EXIT

{
  echo "# Auto-generated by scripts/env_probe.sh — do not edit by hand."
  echo "# Refresh: scripts/env_probe.sh   Freshness gate: scripts/env_probe.sh --check"
  echo "# Behavior rule: .agents/rules/environment-truth.md (probe, don't recall)"
  echo "host: ${HOST_MARKER}"
  echo "probed_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "ttl_days: ${TTL_DAYS}"
  echo "capabilities:"
  echo "  docker: $(probe_docker)"
  echo "  ansible_playbook: $(ver_or_absent ansible-playbook)"
  echo "  ansible_lint: $(ver_or_absent ansible-lint)"
  echo "  yamllint: $(ver_or_absent yamllint)"
  echo "  python3: $(ver_or_absent python3)"
  echo "  uv: $(ver_or_absent uv)"
  echo "  pip_audit: $(ver_or_absent pip-audit)"
  echo "  trivy: $(ver_or_absent trivy)"
  echo "  gh: $(probe_gh)"
  echo "  git_push: $(probe_git_push)"
  echo "  make: $(ver_or_absent make)"
  echo "  jq: $(ver_or_absent jq)"
  echo "host_overrides:"
  if have ansible-playbook; then
    echo "  - \"host ansible toolchain present; make targets and direct ansible-playbook both work\""
  else
    echo "  - \"ansible not on PATH: prefer project make targets or containerized ansible; do not retry bare ansible-playbook\""
  fi
  if have docker && docker version >/dev/null 2>&1; then
    echo "  - \"docker daemon up: local container-based gates (compose builds, molecule, etc.) runnable\""
  else
    echo "  - \"docker unavailable: container gates must be delegated; record as blocked with this registry entry as probe evidence\""
  fi
  echo "command_truth: \"task->command mapping is per-project — see that project's testing/governance docs; this registry carries host capability facts + host-conditional hints only\""
} > "$REGISTRY_TMP"

mv "$REGISTRY_TMP" "$REGISTRY_FILE"
echo "env-probe: wrote ${REGISTRY_FILE}"
sed -n '4,8p' "$REGISTRY_FILE"
